{
    "tests/prague/eip7702_set_code_tx/test_invalid_tx.py::test_invalid_tx_invalid_auth_chain_id[fork_Prague-transaction_test-non_zero_address-auth_chain_id=2**256]": {
        "result": {
            "Prague": {
                "intrinsicGas": "0x00",
                "exception": "TransactionException.TYPE_4_INVALID_AUTHORIZATION_FORMAT"
            }
        },
        "txbytes": "0x04f8e201808007830186a09400000000000000000000000000000000000000008080c0f87df87ba10100000000000000000000000000000000000000000000000000000000000000009400000000000000000000000000000000000000018080a0a03d0f9370fd49783277905659b012549d4fdf5f10d23c9cced15ce19c7a9befa05778b8fdfe23f8f1332f9fa72ee0431005843b784446e5d210b82072969faeb501a05f3f72bb2f6af6da0ba29ea959faebaa4673fb7a8b6282f790e6e3fd7f422f7da02ab12ecea807cffb6925c660e4764e2679228e4919b2e053f391ea36cddf6fe0",
        "_info": {
            "hash": "0x4788c8d0e7f1876a99089f06642c7cfea5fd7da89bae7aa3f6e5756deabec50e",
            "comment": "`execution-spec-tests` generated test",
            "filling-transition-tool": "ethereum-spec-evm-resolver 0.0.5",
            "description": "Test function documentation:\n\n    Test sending a transaction where the chain id field of an authorization overflows the\n    maximum value.",
            "url": "https://github.com/ethereum/execution-spec-tests/blob/2c4d277d2fb7d97333c089b0718ac8d26a95d523/tests/prague/eip7702_set_code_tx/test_invalid_tx.py#L100",
            "fixture_format": "transaction_test",
            "reference-spec": "https://github.com/ethereum/EIPs/blob/master/EIPS/eip-7702.md",
            "reference-spec-version": "4334df83395693dc3f629bb43c18320d9e22e8c9",
            "eels-resolution": {
                "git-url": "https://github.com/ethereum/execution-specs.git",
                "branch": "devnets/prague/6",
                "commit": "a25a8ab3a2989b15baac19eb327325e442342a60"
            }
        }
    },
    "tests/prague/eip7702_set_code_tx/test_invalid_tx.py::test_invalid_tx_invalid_auth_chain_id[fork_Prague-transaction_test-reset_delegation_address-auth_chain_id=2**256]": {
        "result": {
            "Prague": {
                "intrinsicGas": "0x00",
                "exception": "TransactionException.TYPE_4_INVALID_AUTHORIZATION_FORMAT"
            }
        },
        "txbytes": "0x04f8e201808007830186a09400000000000000000000000000000000000000008080c0f87df87ba10100000000000000000000000000000000000000000000000000000000000000009400000000000000000000000000000000000000008080a039863a7e82aa21fcc5419c8dce801a17af414a41d0cf0f624b51c48d96862452a012548bdcb1adee8a0d249ef297c44a9fb21016a730d03eb4df726527a225b5eb80a062528eeaefe52625829af12c801fe7848806e339a74191dbdd05cf3b032af2f1a06ecdf23a484a581009d466d3f1623a6f56fc1dfd3760790784adbc5c260d8693",
        "_info": {
            "hash": "0x1da192add784c436b685b2a80b9bf7753f8472c53b7d48686c11742d2fad86f2",
            "comment": "`execution-spec-tests` generated test",
            "filling-transition-tool": "ethereum-spec-evm-resolver 0.0.5",
            "description": "Test function documentation:\n\n    Test sending a transaction where the chain id field of an authorization overflows the\n    maximum value.",
            "url": "https://github.com/ethereum/execution-spec-tests/blob/2c4d277d2fb7d97333c089b0718ac8d26a95d523/tests/prague/eip7702_set_code_tx/test_invalid_tx.py#L100",
            "fixture_format": "transaction_test",
            "reference-spec": "https://github.com/ethereum/EIPs/blob/master/EIPS/eip-7702.md",
            "reference-spec-version": "4334df83395693dc3f629bb43c18320d9e22e8c9",
            "eels-resolution": {
                "git-url": "https://github.com/ethereum/execution-specs.git",
                "branch": "devnets/prague/6",
                "commit": "a25a8ab3a2989b15baac19eb327325e442342a60"
            }
        }
    }
}
